from enum import Enum


SCORE_THRESHOLD = 0.1
COURSE_PARSE_TRAIN_TIMEOUT_S = 300  # seconds
COURSE_PARSE_TRAIN_INTERVAL_S = 1800  # seconds
COURSE_MODEL_RELOAD_DELAY_S = 3600  # seconds


class TFIDF_MODELS(Enum):
    POST = 0
    I_ANSWER = 1
    S_ANSWER = 2
    FOLLOWUP = 3
